### ISSUE TITLE
Can't use wifi anymore

### ISSUE THREAD

**Issue by aditya342a** [venus342/Wmon---Monitor-Mode#1]
After using reaver, it doesn't stop monitor mode. Tried rebooting, flashing stock rom, even uninstalled all your apps etc. Still can't disable monitor mode

**Comment by venus342** [comment]
That's a issue with the chipset. Reflash the driver included. As for now, we can not do anything to that. But, thanks for reporting the issue.

**Comment by aditya342a** [comment]
Don't close the issue, the problem is still there!
Close it after solving it

**Comment by venus342** [comment]
Please reopen the issue if you still have problems. Also, provide proper explanations and logcat. 
Thanks.
