### ISSUE TITLE
beta tester

### ISSUE THREAD

**Issue by cabilyo** [venus342/Wmon---Monitor-Mode#3]
HI ,
I would like ti join the beta testing group.
cabilyo@yahoo.com
S8 plus.
Thanks.

**Comment by ozsteyr** [comment]
I would like also. Please

**ozsteyr@hotmail.com**

**Comment by venus342** [comment]
Please leave your email. We'll contact you soon 👍

**Comment by bozwald** [comment]
il Beta test please s8+ @bozwald on telegram

**Comment by venus342** [comment]
Please contact venus342.in@hotmail.com for follow-up.
Also, I'll contact you back soon.

**Comment by vwadicted** [comment]
i have a s8 SM-G950F , my e-mail is vw_adicted@hotmail.com . i have alot of experience with rooting and installing mods and have al the develep softeare for android installed

**Comment by venus342** [comment]
The beta testers who were selected will be contacted soon.
